### ISSUE TITLE
No Licence file

### ISSUE THREAD

**Issue by DavidRobb** [phoenixredwolf/prodweb#4]
Many thanks for putting this repo in the public domain.

I'm looking at creating a website using kobweb and would like to use some of the ideas you have shown here.

Any chance you could add a licence to this repo so that I know where I stand on this.

Many thanks.

**Comment by phoenixredwolf** [comment]
License added. If you have any questions about Kobweb, feel free to contact me. Also, I would advise joining the Kobweb discord.

From: David Robb ***@***.***>
Sent: Tuesday, November 28, 2023 7:17 AM
To: phoenixredwolf/prodweb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [phoenixredwolf/prodweb] No Licence file (Issue #4)


Many thanks for putting this repo in the public domain.

I'm looking at creating a website using kobweb and would like to use some of the ideas you have shown here.

Any chance you could add a licence to this repo so that I know where I stand on this.

Many thanks.
